version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    security-updates-only: false
    open-pull-requests-limit: 5
